### ISSUE TITLE
close the v0.2.0 milestone

### ISSUE THREAD

**Issue by gregoryguillou** [dontpanicdao/starknet-burner#22]
## Objectives
make sure the milestore is managed

## Success Criterias
the following must be covered:
- [x] the flow should be working
- [x] the flow must be documented
- [x] the version must be tagged and released
- [x] we should make sure we have learned from the development
