### ISSUE TITLE
v0.3.0 milestone (closing)

### ISSUE THREAD

**Issue by gregoryguillou** [dontpanicdao/starknet-burner#26]
## Objectives
The welcome of the burner wallet by the community and the many conversations at the encode club Paris Hackathon in July 2022 that the [burner wallet have won](https://medium.com/encode-club/starknet-paris-hack-by-encode-and-activate-summary-and-prizewinners-336cbca17a5b), raised the expectation bar a lot. 💯 to everyone who helped with it.

The short term roadmap will focus on:
- leveraging the work done on the session key. we will however revisit the security model with (1) an re-architecture based on a iframe/sandbox ; (2) the addition of control over the contract in the plugin and (3) additional control flows involving 2 session keys
- helping dapps, expecially mobile dapps to benefit from the burner. Good candidates are games and social experiments
- audit the code to make sure this is okay to go live with the wallet.
- rewriting the wallet part in React to help people that would contribute. (Event if I remain convinced that svelte is a better choice).

On the other hand `drone` that will remain pretty much the same for now, since we understand the concern of wallets like Argent-X to control what it is running. 

## Success Criterias
The goals as we can imagine it for now is:
- [x] move the burner into an iframe with a clear interface
- [x] the injection of `window.starknet.burner` so that the burner wallet can be used by starknet-js
- [x] the move of as many as possible of the features of the burner in vanilla js to help with future ports/implementations
- [x] the rewriting of the burner in ReactJS 
- [x] a better documentation
- [ ] a good set of tests

**Comment by gregoryguillou** [comment]
v0.3.0 has been release now.
