### ISSUE TITLE
milestone v0.4.0 (tbd)

### ISSUE THREAD

**Issue by gregoryguillou** [dontpanicdao/starknet-burner#31]
## Objectives
The objective of this milestone is to have a full example of the burner wallet working from a separate app. We might want to have it in a separate repository. We are bullish on `Starkpilled` : a protocol that would allow people to send STRK to people they like for nothing.. 

## Prerequisites
the 0.3.0 milestone should be completed and the wallet published on npmjs.

## Success Criterias
the following must be covered:
- [x] We should be able to connect to the burner wallet
- [x] We should be able to recognize/capture an address from a QRcode
- [x] The app should be a PWA working on iPhone and Android
- [x] We should be able to Grant pills from some outside signed message (check a Faucet)
- [x] We should have a good documentation explaining how to use the wallet

**Comment by gregoryguillou** [comment]
It ends up all the features for 0.4.0 will actually be part of 0.3.0. This issue with be close in consequence
