### ISSUE TITLE
Prepare next Milestone

### ISSUE THREAD

**Issue by gregoryguillou** [dontpanicdao/starknet-burner#7]
## Objective

This should provide some templates for issues and PR as well as the plan for the next milestone

## Success Criterias

- [x] We should have the Github templates for PR and Issues
- [x] We should have a v0.2.0 milestone with a clear objective and the associated issues.
- [x] The review from the v0.1.0 milestone should be done. We should make sure (1) everything is covered ; (2) we have the docs and (3) we know what we have learned
- [x] Tag the branch
